// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: frameo.proto

// SPDX-License-Identifier: GPL-3.0-or-later
//
// Frameo app-layer protocol, reconstructed from net.frameo.app v1.40.5 (jadx).
// Field numbers/types decoded from GeneratedMessageLite newMessageInfo strings.
// NOTE: several 64-bit ids are sint64 (zigzag) on the wire — do NOT change to
// int64 or decoding breaks. Verified against the decompiled info strings.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media_Type int32

const (
	Media_PICTURE          Media_Type = 0
	Media_PROFILE_PICTURE  Media_Type = 1
	Media_VIDEO_WITH_THUMB Media_Type = 2
	Media_PICTURE_THUMB    Media_Type = 3
	Media_GREETING         Media_Type = 4
	Media_GREETING_THUMB   Media_Type = 5
	Media_VIDEO_THUMB      Media_Type = 6
	Media_VIDEO_THUMB_FULL Media_Type = 7
)

// Enum value maps for Media_Type.
var (
	Media_Type_name = map[int32]string{
		0: "PICTURE",
		1: "PROFILE_PICTURE",
		2: "VIDEO_WITH_THUMB",
		3: "PICTURE_THUMB",
		4: "GREETING",
		5: "GREETING_THUMB",
		6: "VIDEO_THUMB",
		7: "VIDEO_THUMB_FULL",
	}
	Media_Type_value = map[string]int32{
		"PICTURE":          0,
		"PROFILE_PICTURE":  1,
		"VIDEO_WITH_THUMB": 2,
		"PICTURE_THUMB":    3,
		"GREETING":         4,
		"GREETING_THUMB":   5,
		"VIDEO_THUMB":      6,
		"VIDEO_THUMB_FULL": 7,
	}
)

func (x Media_Type) Enum() *Media_Type {
	p := new(Media_Type)
	*p = x
	return p
}

func (x Media_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Media_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_frameo_proto_enumTypes[0].Descriptor()
}

func (Media_Type) Type() protoreflect.EnumType {
	return &file_frameo_proto_enumTypes[0]
}

func (x Media_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Media_Type.Descriptor instead.
func (Media_Type) EnumDescriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{0, 0}
}

type Media_ScaleType int32

const (
	Media_NONE              Media_ScaleType = 0
	Media_FIT_INSIDE        Media_ScaleType = 1
	Media_CENTER_POINT_CROP Media_ScaleType = 2
)

// Enum value maps for Media_ScaleType.
var (
	Media_ScaleType_name = map[int32]string{
		0: "NONE",
		1: "FIT_INSIDE",
		2: "CENTER_POINT_CROP",
	}
	Media_ScaleType_value = map[string]int32{
		"NONE":              0,
		"FIT_INSIDE":        1,
		"CENTER_POINT_CROP": 2,
	}
)

func (x Media_ScaleType) Enum() *Media_ScaleType {
	p := new(Media_ScaleType)
	*p = x
	return p
}

func (x Media_ScaleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Media_ScaleType) Descriptor() protoreflect.EnumDescriptor {
	return file_frameo_proto_enumTypes[1].Descriptor()
}

func (Media_ScaleType) Type() protoreflect.EnumType {
	return &file_frameo_proto_enumTypes[1]
}

func (x Media_ScaleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Media_ScaleType.Descriptor instead.
func (Media_ScaleType) EnumDescriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{0, 1}
}

// Recovered from the v1.40.5 decompile; frame->client only.
type Error_Code int32

const (
	Error_NONE                      Error_Code = 0
	Error_UNAUTHORIZED              Error_Code = 1
	Error_SERVER_ERROR              Error_Code = 2
	Error_BAD_REQUEST               Error_Code = 3
	Error_GENERIC_FAILURE           Error_Code = 4
	Error_MISSING_PERMISSION        Error_Code = 5
	Error_MISSING_MEDIA_ITEM        Error_Code = 6
	Error_FAILED_SENDING_MEDIA_ITEM Error_Code = 7
	Error_NOT_FOUND                 Error_Code = 8
	Error_DECLINED                  Error_Code = 9
)

// Enum value maps for Error_Code.
var (
	Error_Code_name = map[int32]string{
		0: "NONE",
		1: "UNAUTHORIZED",
		2: "SERVER_ERROR",
		3: "BAD_REQUEST",
		4: "GENERIC_FAILURE",
		5: "MISSING_PERMISSION",
		6: "MISSING_MEDIA_ITEM",
		7: "FAILED_SENDING_MEDIA_ITEM",
		8: "NOT_FOUND",
		9: "DECLINED",
	}
	Error_Code_value = map[string]int32{
		"NONE":                      0,
		"UNAUTHORIZED":              1,
		"SERVER_ERROR":              2,
		"BAD_REQUEST":               3,
		"GENERIC_FAILURE":           4,
		"MISSING_PERMISSION":        5,
		"MISSING_MEDIA_ITEM":        6,
		"FAILED_SENDING_MEDIA_ITEM": 7,
		"NOT_FOUND":                 8,
		"DECLINED":                  9,
	}
)

func (x Error_Code) Enum() *Error_Code {
	p := new(Error_Code)
	*p = x
	return p
}

func (x Error_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_frameo_proto_enumTypes[2].Descriptor()
}

func (Error_Code) Type() protoreflect.EnumType {
	return &file_frameo_proto_enumTypes[2]
}

func (x Error_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Code.Descriptor instead.
func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{9, 0}
}

type FrameInfo_HasBackup int32

const (
	FrameInfo_HB_UNKNOWN FrameInfo_HasBackup = 0
)

// Enum value maps for FrameInfo_HasBackup.
var (
	FrameInfo_HasBackup_name = map[int32]string{
		0: "HB_UNKNOWN",
	}
	FrameInfo_HasBackup_value = map[string]int32{
		"HB_UNKNOWN": 0,
	}
)

func (x FrameInfo_HasBackup) Enum() *FrameInfo_HasBackup {
	p := new(FrameInfo_HasBackup)
	*p = x
	return p
}

func (x FrameInfo_HasBackup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameInfo_HasBackup) Descriptor() protoreflect.EnumDescriptor {
	return file_frameo_proto_enumTypes[3].Descriptor()
}

func (FrameInfo_HasBackup) Type() protoreflect.EnumType {
	return &file_frameo_proto_enumTypes[3]
}

func (x FrameInfo_HasBackup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameInfo_HasBackup.Descriptor instead.
func (FrameInfo_HasBackup) EnumDescriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{11, 0}
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // TOTAL bytes of the full file (receiver waits for this many)
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	CenterPointX  float32                `protobuf:"fixed32,3,opt,name=center_point_x,json=centerPointX,proto3" json:"center_point_x,omitempty"` // crop focus, 0..1
	CenterPointY  float32                `protobuf:"fixed32,4,opt,name=center_point_y,json=centerPointY,proto3" json:"center_point_y,omitempty"`
	FileExtension string                 `protobuf:"bytes,5,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"` // e.g. "jpg"
	Id            int64                  `protobuf:"zigzag64,6,opt,name=id,proto3" json:"id,omitempty"`                                         // client-chosen media id; keys the transfer + cache file
	Type          Media_Type             `protobuf:"varint,7,opt,name=type,proto3,enum=frameo.Media_Type" json:"type,omitempty"`
	Extra         []*Extra               `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty"`                                   // thumbnail descriptor(s); extra[0].size = thumb byte count
	CaptureDate   int64                  `protobuf:"zigzag64,9,opt,name=capture_date,json=captureDate,proto3" json:"capture_date,omitempty"` // epoch millis
	ContentId     int64                  `protobuf:"zigzag64,10,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	ScaleType     Media_ScaleType        `protobuf:"varint,12,opt,name=scale_type,json=scaleType,proto3,enum=frameo.Media_ScaleType" json:"scale_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_frameo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Media) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Media) GetCenterPointX() float32 {
	if x != nil {
		return x.CenterPointX
	}
	return 0
}

func (x *Media) GetCenterPointY() float32 {
	if x != nil {
		return x.CenterPointY
	}
	return 0
}

func (x *Media) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetType() Media_Type {
	if x != nil {
		return x.Type
	}
	return Media_PICTURE
}

func (x *Media) GetExtra() []*Extra {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Media) GetCaptureDate() int64 {
	if x != nil {
		return x.CaptureDate
	}
	return 0
}

func (x *Media) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Media) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Media) GetScaleType() Media_ScaleType {
	if x != nil {
		return x.ScaleType
	}
	return Media_NONE
}

type Extra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // byte count of this extra stream (e.g. thumbnail)
	FileExtension string                 `protobuf:"bytes,2,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extra) Reset() {
	*x = Extra{}
	mi := &file_frameo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extra) ProtoMessage() {}

func (x *Extra) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extra.ProtoReflect.Descriptor instead.
func (*Extra) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{1}
}

func (x *Extra) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Extra) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

// The actual file bytes. Sent (in order) after the Media header. The receiver
// appends data to receiving_cache/<Media.id> until it has Media.size bytes.
type MediaDataSegment struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Data                         []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RequiresAcknowledgeReceiptId int64                  `protobuf:"varint,16,opt,name=requires_acknowledge_receipt_id,json=requiresAcknowledgeReceiptId,proto3" json:"requires_acknowledge_receipt_id,omitempty"` // set on the last segment; frame replies AcknowledgeReceipt
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *MediaDataSegment) Reset() {
	*x = MediaDataSegment{}
	mi := &file_frameo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaDataSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaDataSegment) ProtoMessage() {}

func (x *MediaDataSegment) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaDataSegment.ProtoReflect.Descriptor instead.
func (*MediaDataSegment) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{2}
}

func (x *MediaDataSegment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MediaDataSegment) GetRequiresAcknowledgeReceiptId() int64 {
	if x != nil {
		return x.RequiresAcknowledgeReceiptId
	}
	return 0
}

// Ask the frame for one stored photo. The frame answers with a Media header
// followed by MediaDataSegment bytes -- the same pair the upload path uses,
// pointed the other way. Leave width/height at zero for the full-resolution
// file; set both to a square bound to have the frame scale it first.
type GetMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"zigzag64,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedia) Reset() {
	*x = GetMedia{}
	mi := &file_frameo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedia) ProtoMessage() {}

func (x *GetMedia) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedia.ProtoReflect.Descriptor instead.
func (*GetMedia) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{3}
}

func (x *GetMedia) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *GetMedia) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetMedia) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type MediaUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUpdate) Reset() {
	*x = MediaUpdate{}
	mi := &file_frameo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUpdate) ProtoMessage() {}

func (x *MediaUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUpdate.ProtoReflect.Descriptor instead.
func (*MediaUpdate) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{4}
}

func (x *MediaUpdate) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

// Resume a partially-transferred media (client asks, frame answers received_bytes)
type ResumeTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"zigzag64,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	ContentId     int64                  `protobuf:"zigzag64,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTransfer) Reset() {
	*x = ResumeTransfer{}
	mi := &file_frameo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTransfer) ProtoMessage() {}

func (x *ResumeTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTransfer.ProtoReflect.Descriptor instead.
func (*ResumeTransfer) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeTransfer) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *ResumeTransfer) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type ResumeTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"zigzag64,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	ContentId     int64                  `protobuf:"zigzag64,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ReceivedBytes int32                  `protobuf:"varint,3,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTransferResponse) Reset() {
	*x = ResumeTransferResponse{}
	mi := &file_frameo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTransferResponse) ProtoMessage() {}

func (x *ResumeTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTransferResponse.ProtoReflect.Descriptor instead.
func (*ResumeTransferResponse) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeTransferResponse) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *ResumeTransferResponse) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *ResumeTransferResponse) GetReceivedBytes() int32 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

// ======================================================================
// Transport fragmentation wrapper  -- from PBMediaTransfer.MultiPartMessage
// Any inner frame larger than 16416 bytes is split into these (see PROTOCOL.md).
// ======================================================================
type MultiPartMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"zigzag64,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`     // same for all fragments of one inner frame (System.currentTimeMillis())
	MessageSize   int32                  `protobuf:"varint,2,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"` // total length of the reassembled inner frame
	DataIndex     int32                  `protobuf:"varint,3,opt,name=data_index,json=dataIndex,proto3" json:"data_index,omitempty"`       // 0-based fragment index
	MessageData   []byte                 `protobuf:"bytes,4,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`  // fragment payload (<= 16316 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPartMessage) Reset() {
	*x = MultiPartMessage{}
	mi := &file_frameo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPartMessage) ProtoMessage() {}

func (x *MultiPartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPartMessage.ProtoReflect.Descriptor instead.
func (*MultiPartMessage) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{7}
}

func (x *MultiPartMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MultiPartMessage) GetMessageSize() int32 {
	if x != nil {
		return x.MessageSize
	}
	return 0
}

func (x *MultiPartMessage) GetDataIndex() int32 {
	if x != nil {
		return x.DataIndex
	}
	return 0
}

func (x *MultiPartMessage) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

// ======================================================================
// Common  -- from PBCommon
// ======================================================================
type AcknowledgeReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcknowledgeId int64                  `protobuf:"varint,1,opt,name=acknowledge_id,json=acknowledgeId,proto3" json:"acknowledge_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeReceipt) Reset() {
	*x = AcknowledgeReceipt{}
	mi := &file_frameo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeReceipt) ProtoMessage() {}

func (x *AcknowledgeReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeReceipt.ProtoReflect.Descriptor instead.
func (*AcknowledgeReceipt) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{8}
}

func (x *AcknowledgeReceipt) GetAcknowledgeId() int64 {
	if x != nil {
		return x.AcknowledgeId
	}
	return 0
}

func (x *AcknowledgeReceipt) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Error_Code             `protobuf:"varint,1,opt,name=code,proto3,enum=frameo.Error_Code" json:"code,omitempty"`
	AdditionalInt int32                  `protobuf:"varint,2,opt,name=additional_int,json=additionalInt,proto3" json:"additional_int,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_frameo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() Error_Code {
	if x != nil {
		return x.Code
	}
	return Error_NONE
}

func (x *Error) GetAdditionalInt() int32 {
	if x != nil {
		return x.AdditionalInt
	}
	return 0
}

// ======================================================================
// Basic / handshake  -- from PBBasic
// ======================================================================
type GetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfo) Reset() {
	*x = GetInfo{}
	mi := &file_frameo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo) ProtoMessage() {}

func (x *GetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo.ProtoReflect.Descriptor instead.
func (*GetInfo) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{10}
}

type FrameInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Name                      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Placement                 string                 `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
	ScreenWidth               int32                  `protobuf:"varint,3,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight              int32                  `protobuf:"varint,4,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	HasPermissionSharePairing bool                   `protobuf:"varint,5,opt,name=has_permission_share_pairing,json=hasPermissionSharePairing,proto3" json:"has_permission_share_pairing,omitempty"`
	HasPermissionToBackup     bool                   `protobuf:"varint,6,opt,name=has_permission_to_backup,json=hasPermissionToBackup,proto3" json:"has_permission_to_backup,omitempty"`
	HasBackup                 FrameInfo_HasBackup    `protobuf:"varint,7,opt,name=has_backup,json=hasBackup,proto3,enum=frameo.FrameInfo_HasBackup" json:"has_backup,omitempty"` // enum, values not reconstructed
	HasPermissionViewPhotos   bool                   `protobuf:"varint,8,opt,name=has_permission_view_photos,json=hasPermissionViewPhotos,proto3" json:"has_permission_view_photos,omitempty"`
	HasPermissionManagePhotos bool                   `protobuf:"varint,9,opt,name=has_permission_manage_photos,json=hasPermissionManagePhotos,proto3" json:"has_permission_manage_photos,omitempty"`
	FrameCapabilities         *FrameCapabilities     `protobuf:"bytes,10,opt,name=frame_capabilities,json=frameCapabilities,proto3" json:"frame_capabilities,omitempty"`
	AsyncInformation          *AsyncInformation      `protobuf:"bytes,11,opt,name=async_information,json=asyncInformation,proto3" json:"async_information,omitempty"`
	CurrentState              int32                  `protobuf:"varint,12,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`       // enum
	ApiEnvironment            int32                  `protobuf:"varint,13,opt,name=api_environment,json=apiEnvironment,proto3" json:"api_environment,omitempty"` // enum
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *FrameInfo) Reset() {
	*x = FrameInfo{}
	mi := &file_frameo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInfo) ProtoMessage() {}

func (x *FrameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInfo.ProtoReflect.Descriptor instead.
func (*FrameInfo) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{11}
}

func (x *FrameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FrameInfo) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *FrameInfo) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *FrameInfo) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *FrameInfo) GetHasPermissionSharePairing() bool {
	if x != nil {
		return x.HasPermissionSharePairing
	}
	return false
}

func (x *FrameInfo) GetHasPermissionToBackup() bool {
	if x != nil {
		return x.HasPermissionToBackup
	}
	return false
}

func (x *FrameInfo) GetHasBackup() FrameInfo_HasBackup {
	if x != nil {
		return x.HasBackup
	}
	return FrameInfo_HB_UNKNOWN
}

func (x *FrameInfo) GetHasPermissionViewPhotos() bool {
	if x != nil {
		return x.HasPermissionViewPhotos
	}
	return false
}

func (x *FrameInfo) GetHasPermissionManagePhotos() bool {
	if x != nil {
		return x.HasPermissionManagePhotos
	}
	return false
}

func (x *FrameInfo) GetFrameCapabilities() *FrameCapabilities {
	if x != nil {
		return x.FrameCapabilities
	}
	return nil
}

func (x *FrameInfo) GetAsyncInformation() *AsyncInformation {
	if x != nil {
		return x.AsyncInformation
	}
	return nil
}

func (x *FrameInfo) GetCurrentState() int32 {
	if x != nil {
		return x.CurrentState
	}
	return 0
}

func (x *FrameInfo) GetApiEnvironment() int32 {
	if x != nil {
		return x.ApiEnvironment
	}
	return 0
}

type FrameCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxVideoWidth  int32                  `protobuf:"varint,1,opt,name=max_video_width,json=maxVideoWidth,proto3" json:"max_video_width,omitempty"`
	MaxVideoHeight int32                  `protobuf:"varint,2,opt,name=max_video_height,json=maxVideoHeight,proto3" json:"max_video_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FrameCapabilities) Reset() {
	*x = FrameCapabilities{}
	mi := &file_frameo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameCapabilities) ProtoMessage() {}

func (x *FrameCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameCapabilities.ProtoReflect.Descriptor instead.
func (*FrameCapabilities) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{12}
}

func (x *FrameCapabilities) GetMaxVideoWidth() int32 {
	if x != nil {
		return x.MaxVideoWidth
	}
	return 0
}

func (x *FrameCapabilities) GetMaxVideoHeight() int32 {
	if x != nil {
		return x.MaxVideoHeight
	}
	return 0
}

type AsyncInformation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChiaId           string                 `protobuf:"bytes,1,opt,name=chia_id,json=chiaId,proto3" json:"chia_id,omitempty"`
	HasActiveSession bool                   `protobuf:"varint,2,opt,name=has_active_session,json=hasActiveSession,proto3" json:"has_active_session,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AsyncInformation) Reset() {
	*x = AsyncInformation{}
	mi := &file_frameo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncInformation) ProtoMessage() {}

func (x *AsyncInformation) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncInformation.ProtoReflect.Descriptor instead.
func (*AsyncInformation) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{13}
}

func (x *AsyncInformation) GetChiaId() string {
	if x != nil {
		return x.ChiaId
	}
	return ""
}

func (x *AsyncInformation) GetHasActiveSession() bool {
	if x != nil {
		return x.HasActiveSession
	}
	return false
}

type ClientInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserAccountId    string                 `protobuf:"bytes,2,opt,name=user_account_id,json=userAccountId,proto3" json:"user_account_id,omitempty"`
	ProfilePictureId int64                  `protobuf:"zigzag64,3,opt,name=profile_picture_id,json=profilePictureId,proto3" json:"profile_picture_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_frameo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{14}
}

func (x *ClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientInfo) GetUserAccountId() string {
	if x != nil {
		return x.UserAccountId
	}
	return ""
}

func (x *ClientInfo) GetProfilePictureId() int64 {
	if x != nil {
		return x.ProfilePictureId
	}
	return 0
}

// Asks the frame's owner to grant a permission (type 27): 1 = view photos,
// 3 = manage photos. Shape read from yasoob/frameo-client, not from the app.
type RequestPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    int32                  `protobuf:"varint,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPermission) Reset() {
	*x = RequestPermission{}
	mi := &file_frameo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPermission) ProtoMessage() {}

func (x *RequestPermission) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPermission.ProtoReflect.Descriptor instead.
func (*RequestPermission) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{15}
}

func (x *RequestPermission) GetPermission() int32 {
	if x != nil {
		return x.Permission
	}
	return 0
}

type EncryptedData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nonce            []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EncryptedMessage string                 `protobuf:"bytes,2,opt,name=encrypted_message,json=encryptedMessage,proto3" json:"encrypted_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	mi := &file_frameo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{16}
}

func (x *EncryptedData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedData) GetEncryptedMessage() string {
	if x != nil {
		return x.EncryptedMessage
	}
	return ""
}

type PairingCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairingCode   string                 `protobuf:"bytes,1,opt,name=pairing_code,json=pairingCode,proto3" json:"pairing_code,omitempty"`
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingCode) Reset() {
	*x = PairingCode{}
	mi := &file_frameo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingCode) ProtoMessage() {}

func (x *PairingCode) ProtoReflect() protoreflect.Message {
	mi := &file_frameo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingCode.ProtoReflect.Descriptor instead.
func (*PairingCode) Descriptor() ([]byte, []int) {
	return file_frameo_proto_rawDescGZIP(), []int{17}
}

func (x *PairingCode) GetPairingCode() string {
	if x != nil {
		return x.PairingCode
	}
	return ""
}

func (x *PairingCode) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_frameo_proto protoreflect.FileDescriptor

const file_frameo_proto_rawDesc = "" +
	"\n" +
	"\fframeo.proto\x12\x06frameo\"\xff\x04\n" +
	"\x05Media\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12$\n" +
	"\x0ecenter_point_x\x18\x03 \x01(\x02R\fcenterPointX\x12$\n" +
	"\x0ecenter_point_y\x18\x04 \x01(\x02R\fcenterPointY\x12%\n" +
	"\x0efile_extension\x18\x05 \x01(\tR\rfileExtension\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x12R\x02id\x12&\n" +
	"\x04type\x18\a \x01(\x0e2\x12.frameo.Media.TypeR\x04type\x12#\n" +
	"\x05extra\x18\b \x03(\v2\r.frameo.ExtraR\x05extra\x12!\n" +
	"\fcapture_date\x18\t \x01(\x12R\vcaptureDate\x12\x1d\n" +
	"\n" +
	"content_id\x18\n" +
	" \x01(\x12R\tcontentId\x12#\n" +
	"\x05error\x18\v \x01(\v2\r.frameo.ErrorR\x05error\x126\n" +
	"\n" +
	"scale_type\x18\f \x01(\x0e2\x17.frameo.Media.ScaleTypeR\tscaleType\"\x9a\x01\n" +
	"\x04Type\x12\v\n" +
	"\aPICTURE\x10\x00\x12\x13\n" +
	"\x0fPROFILE_PICTURE\x10\x01\x12\x14\n" +
	"\x10VIDEO_WITH_THUMB\x10\x02\x12\x11\n" +
	"\rPICTURE_THUMB\x10\x03\x12\f\n" +
	"\bGREETING\x10\x04\x12\x12\n" +
	"\x0eGREETING_THUMB\x10\x05\x12\x0f\n" +
	"\vVIDEO_THUMB\x10\x06\x12\x14\n" +
	"\x10VIDEO_THUMB_FULL\x10\a\"<\n" +
	"\tScaleType\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"FIT_INSIDE\x10\x01\x12\x15\n" +
	"\x11CENTER_POINT_CROP\x10\x02\"B\n" +
	"\x05Extra\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12%\n" +
	"\x0efile_extension\x18\x02 \x01(\tR\rfileExtension\"m\n" +
	"\x10MediaDataSegment\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12E\n" +
	"\x1frequires_acknowledge_receipt_id\x18\x10 \x01(\x03R\x1crequiresAcknowledgeReceiptId\"S\n" +
	"\bGetMedia\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x12R\amediaId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"2\n" +
	"\vMediaUpdate\x12#\n" +
	"\x05media\x18\x01 \x01(\v2\r.frameo.MediaR\x05media\"J\n" +
	"\x0eResumeTransfer\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x12R\amediaId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x12R\tcontentId\"y\n" +
	"\x16ResumeTransferResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x12R\amediaId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x12R\tcontentId\x12%\n" +
	"\x0ereceived_bytes\x18\x03 \x01(\x05R\rreceivedBytes\"\x96\x01\n" +
	"\x10MultiPartMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x12R\tmessageId\x12!\n" +
	"\fmessage_size\x18\x02 \x01(\x05R\vmessageSize\x12\x1d\n" +
	"\n" +
	"data_index\x18\x03 \x01(\x05R\tdataIndex\x12!\n" +
	"\fmessage_data\x18\x04 \x01(\fR\vmessageData\"`\n" +
	"\x12AcknowledgeReceipt\x12%\n" +
	"\x0eacknowledge_id\x18\x01 \x01(\x03R\racknowledgeId\x12#\n" +
	"\x05error\x18\x02 \x01(\v2\r.frameo.ErrorR\x05error\"\x9f\x02\n" +
	"\x05Error\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.frameo.Error.CodeR\x04code\x12%\n" +
	"\x0eadditional_int\x18\x02 \x01(\x05R\radditionalInt\"\xc6\x01\n" +
	"\x04Code\x12\b\n" +
	"\x04NONE\x10\x00\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x01\x12\x10\n" +
	"\fSERVER_ERROR\x10\x02\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x03\x12\x13\n" +
	"\x0fGENERIC_FAILURE\x10\x04\x12\x16\n" +
	"\x12MISSING_PERMISSION\x10\x05\x12\x16\n" +
	"\x12MISSING_MEDIA_ITEM\x10\x06\x12\x1d\n" +
	"\x19FAILED_SENDING_MEDIA_ITEM\x10\a\x12\r\n" +
	"\tNOT_FOUND\x10\b\x12\f\n" +
	"\bDECLINED\x10\t\"\t\n" +
	"\aGetInfo\"\xb5\x05\n" +
	"\tFrameInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tplacement\x18\x02 \x01(\tR\tplacement\x12!\n" +
	"\fscreen_width\x18\x03 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\x04 \x01(\x05R\fscreenHeight\x12?\n" +
	"\x1chas_permission_share_pairing\x18\x05 \x01(\bR\x19hasPermissionSharePairing\x127\n" +
	"\x18has_permission_to_backup\x18\x06 \x01(\bR\x15hasPermissionToBackup\x12:\n" +
	"\n" +
	"has_backup\x18\a \x01(\x0e2\x1b.frameo.FrameInfo.HasBackupR\thasBackup\x12;\n" +
	"\x1ahas_permission_view_photos\x18\b \x01(\bR\x17hasPermissionViewPhotos\x12?\n" +
	"\x1chas_permission_manage_photos\x18\t \x01(\bR\x19hasPermissionManagePhotos\x12H\n" +
	"\x12frame_capabilities\x18\n" +
	" \x01(\v2\x19.frameo.FrameCapabilitiesR\x11frameCapabilities\x12E\n" +
	"\x11async_information\x18\v \x01(\v2\x18.frameo.AsyncInformationR\x10asyncInformation\x12#\n" +
	"\rcurrent_state\x18\f \x01(\x05R\fcurrentState\x12'\n" +
	"\x0fapi_environment\x18\r \x01(\x05R\x0eapiEnvironment\"\x1b\n" +
	"\tHasBackup\x12\x0e\n" +
	"\n" +
	"HB_UNKNOWN\x10\x00\"e\n" +
	"\x11FrameCapabilities\x12&\n" +
	"\x0fmax_video_width\x18\x01 \x01(\x05R\rmaxVideoWidth\x12(\n" +
	"\x10max_video_height\x18\x02 \x01(\x05R\x0emaxVideoHeight\"Y\n" +
	"\x10AsyncInformation\x12\x17\n" +
	"\achia_id\x18\x01 \x01(\tR\x06chiaId\x12,\n" +
	"\x12has_active_session\x18\x02 \x01(\bR\x10hasActiveSession\"v\n" +
	"\n" +
	"ClientInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0fuser_account_id\x18\x02 \x01(\tR\ruserAccountId\x12,\n" +
	"\x12profile_picture_id\x18\x03 \x01(\x12R\x10profilePictureId\"3\n" +
	"\x11RequestPermission\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\x05R\n" +
	"permission\"R\n" +
	"\rEncryptedData\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12+\n" +
	"\x11encrypted_message\x18\x02 \x01(\tR\x10encryptedMessage\"B\n" +
	"\vPairingCode\x12!\n" +
	"\fpairing_code\x18\x01 \x01(\tR\vpairingCode\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttlB.Z,github.com/borje/unframeo/internal/frameo/pbb\x06proto3"

var (
	file_frameo_proto_rawDescOnce sync.Once
	file_frameo_proto_rawDescData []byte
)

func file_frameo_proto_rawDescGZIP() []byte {
	file_frameo_proto_rawDescOnce.Do(func() {
		file_frameo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frameo_proto_rawDesc), len(file_frameo_proto_rawDesc)))
	})
	return file_frameo_proto_rawDescData
}

var file_frameo_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_frameo_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_frameo_proto_goTypes = []any{
	(Media_Type)(0),                // 0: frameo.Media.Type
	(Media_ScaleType)(0),           // 1: frameo.Media.ScaleType
	(Error_Code)(0),                // 2: frameo.Error.Code
	(FrameInfo_HasBackup)(0),       // 3: frameo.FrameInfo.HasBackup
	(*Media)(nil),                  // 4: frameo.Media
	(*Extra)(nil),                  // 5: frameo.Extra
	(*MediaDataSegment)(nil),       // 6: frameo.MediaDataSegment
	(*GetMedia)(nil),               // 7: frameo.GetMedia
	(*MediaUpdate)(nil),            // 8: frameo.MediaUpdate
	(*ResumeTransfer)(nil),         // 9: frameo.ResumeTransfer
	(*ResumeTransferResponse)(nil), // 10: frameo.ResumeTransferResponse
	(*MultiPartMessage)(nil),       // 11: frameo.MultiPartMessage
	(*AcknowledgeReceipt)(nil),     // 12: frameo.AcknowledgeReceipt
	(*Error)(nil),                  // 13: frameo.Error
	(*GetInfo)(nil),                // 14: frameo.GetInfo
	(*FrameInfo)(nil),              // 15: frameo.FrameInfo
	(*FrameCapabilities)(nil),      // 16: frameo.FrameCapabilities
	(*AsyncInformation)(nil),       // 17: frameo.AsyncInformation
	(*ClientInfo)(nil),             // 18: frameo.ClientInfo
	(*RequestPermission)(nil),      // 19: frameo.RequestPermission
	(*EncryptedData)(nil),          // 20: frameo.EncryptedData
	(*PairingCode)(nil),            // 21: frameo.PairingCode
}
var file_frameo_proto_depIdxs = []int32{
	0,  // 0: frameo.Media.type:type_name -> frameo.Media.Type
	5,  // 1: frameo.Media.extra:type_name -> frameo.Extra
	13, // 2: frameo.Media.error:type_name -> frameo.Error
	1,  // 3: frameo.Media.scale_type:type_name -> frameo.Media.ScaleType
	4,  // 4: frameo.MediaUpdate.media:type_name -> frameo.Media
	13, // 5: frameo.AcknowledgeReceipt.error:type_name -> frameo.Error
	2,  // 6: frameo.Error.code:type_name -> frameo.Error.Code
	3,  // 7: frameo.FrameInfo.has_backup:type_name -> frameo.FrameInfo.HasBackup
	16, // 8: frameo.FrameInfo.frame_capabilities:type_name -> frameo.FrameCapabilities
	17, // 9: frameo.FrameInfo.async_information:type_name -> frameo.AsyncInformation
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_frameo_proto_init() }
func file_frameo_proto_init() {
	if File_frameo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frameo_proto_rawDesc), len(file_frameo_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frameo_proto_goTypes,
		DependencyIndexes: file_frameo_proto_depIdxs,
		EnumInfos:         file_frameo_proto_enumTypes,
		MessageInfos:      file_frameo_proto_msgTypes,
	}.Build()
	File_frameo_proto = out.File
	file_frameo_proto_goTypes = nil
	file_frameo_proto_depIdxs = nil
}
